### ISSUE TITLE
Not working with TESTNET

### ISSUE THREAD

**Issue by gustavklopp** [richardkiss/pycoinnet#3]
I'm trying with:
```
$ ku -ua P:foo -n XTN >> ~/.wallet/default/watch_addresses
```
and I've replaced in `examples/wallet.py` : 
```
-23  from pycoinnet.helpers.networks import MAINNET
+23 from pycoinnet.helpers.networks import TESTNET
```
and
```
def wallet_fetch(path, args):
    early_timestamp = calendar.timegm(args.date)
    print("wallet. Fetching.")
-   network = MAINNET
+ network = TESTNET
```

But when doing:
```
$ ./wallet.py fetch
wallet. Fetching.
1 elements; filter size: 3 bytes; 17 hash functions
Traceback (most recent call last):
  File "./wallet.py", line 226, in <module>
    main()
  File "./wallet.py", line 216, in main
    wallet_fetch(path, args)
  File "./wallet.py", line 81, in wallet_fetch
    bloom_filter.add_address(a)
  File "/home/gus/.Envs/btcc/lib/python3.5/site-packages/pycoinnet/bloom.py", line 35, in add_address
    the_hash160 = bitcoin_address_to_hash160_sec(address, address_prefix=address_prefix)
  File "/home/gus/.Envs/btcc/src/pycoin-master/pycoin/encoding.py", line 284, in bitcoin_address_to_hash160_sec
    hash160, actual_prefix = bitcoin_address_to_hash160_sec_with_prefix(bitcoin_address)
  File "/home/gus/.Envs/btcc/src/pycoin-master/pycoin/encoding.py", line 272, in bitcoin_address_to_hash160_sec_with_prefix
    blob = a2b_hashed_base58(bitcoin_address)
  File "/home/gus/.Envs/btcc/src/pycoin-master/pycoin/encoding.py", line 165, in a2b_hashed_base58
    raise EncodingError("hashed base58 has bad checksum %s" % s)
pycoin.encoding.EncodingError: hashed base58 has bad checksum n3MVrx3Foba7F5Nkty18BoZQaNYhrrdUs
```

Thanks!

**Comment by gustavklopp** [comment]
I got it:
in examples/wallet.py:
```
    for a in addresses:
        bloom_filter.add_address(a, address_prefix=b'\x6f') # In TESTNET. address_prefix=b'\0' for MAINNET
```
